# Generated by Django 2.0.7 on 2019-04-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190429_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'stu_info',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StuInfo'),
        ),
    ]
