# Generated by Django 2.0.7 on 2019-04-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190429_1418'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='stu',
        ),
    ]
