# Generated by Django 2.0.7 on 2019-04-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190429_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10, unique=True, verbose_name='课程名')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='c',
            field=models.ManyToManyField(to='app.Course'),
        ),
    ]
