# Generated by Django 2.2.3 on 2020-08-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=1000, verbose_name='图片地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('nick', models.CharField(blank=True, max_length=255, null=True, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='头像地址')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
