# Generated by Django 2.0.7 on 2019-04-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='math',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='数学成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='yuwen',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='语文成绩'),
        ),
    ]
