# Generated by Django 2.2.3 on 2020-08-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20200801_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_id',
            field=models.IntegerField(verbose_name='回复的目标评论'),
        ),
    ]
