# Generated by Django 2.2.3 on 2020-08-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0003_auto_20200801_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='回复的目标评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='root_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='根(一级)评论的id'),
        ),
    ]
