# Generated by Django 2.2.3 on 2020-08-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0004_auto_20200801_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='root_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='circle.Comment', verbose_name='回复的目标评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='circle.Comment', verbose_name='根(一级)评论的id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(default=1, verbose_name='评论层级(属于哪级评论)'),
        ),
    ]
