# Generated by Django 2.2.3 on 2020-08-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0005_auto_20200801_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='add_date',
            new_name='add_time',
        ),
    ]
